// Generated by scripts/generate_control_types.py.
// FastAPI schemas are authoritative; do not edit this file manually.

export type AcceptedContractDraft = {
  operation: "read" | "write" | "delete" | "execute" | "network" | "external_communication" | "credential_access";
  exact_targets: Array<string>;
  environment: "sandbox" | "dev" | "staging" | "production";
  expected_side_effects: Array<string>;
  allowed_effects: Array<string>;
  forbidden_operations?: Array<"read" | "write" | "delete" | "execute" | "network" | "external_communication" | "credential_access">;
  forbidden_effects: Array<string>;
  forbidden_effect_codes?: Array<string>;
  rollback_plan: string;
  dry_run_required: boolean;
  rollback_required?: boolean;
  transaction_required?: boolean;
  backup_required?: boolean;
  expires_in_minutes?: number;
  tool_family?: "shell" | "sentinel_issue_fixture";
};

export type ActionContract = {
  objective: string;
  allowed_operations: Array<"read" | "write" | "delete" | "execute" | "network" | "external_communication" | "credential_access">;
  allowed_tools: Array<string>;
  exact_targets: Array<string>;
  environment: "sandbox" | "dev" | "staging" | "production";
  maximum_scope: "exact" | "directory" | "workspace";
  expected_side_effects: Array<string>;
  allowed_effects?: Array<string>;
  forbidden_operations?: Array<"read" | "write" | "delete" | "execute" | "network" | "external_communication" | "credential_access">;
  forbidden_effects: Array<string>;
  forbidden_effect_codes?: Array<string>;
  rollback_plan: string;
  dry_run_required: boolean;
  rollback_required?: boolean;
  transaction_required?: boolean;
  backup_required?: boolean;
  obligations?: ContractObligations | null;
  environment_context?: Record<string, string>;
  provider_scope?: ProviderScope | null;
  audience_policy?: AudiencePolicy | null;
  approved_payload_sha256?: string | null;
  source_prompt_sha256?: string | null;
  authorization_reference: string;
  version?: number;
  expires_at: string;
};

export type AgentConnectionResponse = {
  host: string;
  status: "never_connected" | "connected" | "disconnected";
  last_seen_at?: string | null;
  last_tool?: string | null;
  last_verdict?: string | null;
  mediated_calls?: number;
  rejected_calls?: number;
  adapter_session_expires_at?: string | null;
};

export type AudiencePolicy = {
  allow_external?: boolean;
  allow_guests?: boolean;
  allow_public?: boolean;
  allow_broadcast?: boolean;
  allow_recipient_expansion?: boolean;
  maximum_recipient_count?: number | null;
  allowed_recipient_ids?: Array<string> | null;
  allowed_audience_resource_ids?: Array<string> | null;
};

export type AuditEvent = {
  event_id?: string;
  sequence_id?: number | null;
  event_type: string;
  timestamp?: string;
  request_id?: string | null;
  user_id?: string | null;
  agent_id?: string | null;
  session_id?: string | null;
  task_id?: string | null;
  contract_id?: string | null;
  contract_version?: number | null;
  environment?: "sandbox" | "dev" | "staging" | "production" | null;
  verdict?: "allow" | "warn" | "confirm_required" | "block" | null;
  reason_codes?: Array<string>;
  details?: Record<string, unknown>;
};

export type CeilingStatusResponse = {
  adapter_kind: string;
  tool_family: string;
  policy_sha256: string;
  expires_at: string;
  expired: boolean;
};

export type ContractObligations = {
  dry_run_required?: boolean;
  rollback_required?: boolean;
  transaction_required?: boolean;
  backup_required?: boolean;
};

export type ContractRecord = {
  contract_id: string;
  task_id: string;
  session_id: string;
  version: number;
  authority_epoch: number;
  authority_event_id?: string | null;
  status: "proposed" | "pending_review" | "active" | "rejected" | "superseded" | "suspended" | "expired" | "revoked";
  contract: ActionContract;
  authorization_source: "trusted_user" | "trusted_host" | "protected_local_ui";
  authorization_reference: string;
  parent_contract_id?: string | null;
  parent_version?: number | null;
  supersedes_version?: number | null;
  superseded_by_version?: number | null;
  preflight_status?: "not_required" | "complete" | "needs_clarification";
  created_at: string;
  updated_at: string;
  expires_at: string;
};

export type ControlCheckResponse = {
  status: "ready" | "unavailable";
  detail: string;
};

export type ControlRuntimeStatus = {
  backend: ControlCheckResponse;
  workspace: ControlCheckResponse;
  docker: ControlCheckResponse;
  rules: ControlCheckResponse;
  demo_mode?: boolean;
  sample_repository?: string | null;
};

export type ControlWorkspaceResponse = {
  name: string;
  canonical_path: string;
  identity_sha256: string;
};

export type DraftQuestionResponse = {
  question_id: string;
  field: string;
  prompt: string;
};

export type DraftSuggestionResponse = {
  field: string;
  value: unknown;
  source: "prompt_explicit" | "prompt_inference" | "deterministic_derivation" | "safe_default";
  requires_review?: true;
};

export type EvaluateResponse = {
  request_id: string;
  verdict: "allow" | "warn" | "confirm_required" | "block";
  risk_score: number;
  risk_tier: "low" | "medium" | "high" | "critical";
  reasons?: Array<string>;
  routing_path: "rules" | "policy" | "model" | "combined" | "confirmation" | "contract" | "approval";
  agent_message: string;
  suggested_safe_actions?: Array<string>;
  confirmation_id?: string | null;
  approval_id?: string | null;
  execution?: ExecutionResult | null;
};

export type ExecutionResult = {
  stdout?: string;
  stderr?: string;
  exit_code?: number | null;
  timed_out?: boolean;
  duration_ms: number;
  error?: string | null;
  stdout_truncated?: boolean;
  stderr_truncated?: boolean;
};

export type FamilyCoverageResponse = {
  family: string;
  status: "mandatory" | "advisory" | "unsupported" | "unavailable";
  basis: string;
  conditions?: Array<string>;
  known_bypasses?: Array<string>;
};

export type IntegrationStatusResponse = {
  gateway: ControlCheckResponse;
  hooks: ControlCheckResponse;
  sandbox: ControlCheckResponse;
  ceiling: CeilingStatusResponse;
  agent: AgentConnectionResponse;
  coverage: Array<FamilyCoverageResponse>;
};

export type PendingApprovalResponse = {
  approval_id: string;
  attempt_id: string;
  operation: string;
  raw_command: string;
  targets: Array<string>;
  effects: Array<string>;
  workspace: string;
  task_id: string;
  contract_id: string;
  contract_version: number;
  authority_epoch: number;
  environment: string;
  reasons: Array<string>;
  expires_at: string;
  family?: string;
  tool?: string | null;
  arguments?: Record<string, unknown>;
};

export type ProviderScope = {
  provider: "slack" | "gmail" | "google_calendar" | "google_drive";
  tenant_id: string;
  resource_account_id?: string | null;
  credential_principal_id: string;
  actor_id?: string | null;
  adapter_id: string;
};

export type ControlStatusResponse = {
  paired?: true;
  supervision_session_id: string;
  session_absolute_expires_at: string;
  workspace: ControlWorkspaceResponse;
  runtime: ControlRuntimeStatus;
  ml_status?: "disabled";
  mandatory_agent_connected?: boolean;
  connection_message?: string;
  integration?: IntegrationStatusResponse | null;
};

export type ActiveAuthorityResponse = {
  active_contract?: ContractRecord | null;
};

export type ApprovalListResponse = {
  approvals: Array<PendingApprovalResponse>;
};

export type ContractDraftRequest = {
  raw_prompt: string;
  accepted_contract?: AcceptedContractDraft | null;
};

export type ContractDraftResponse = {
  prompt_sha256: string;
  suggestions: Array<DraftSuggestionResponse>;
  questions: Array<DraftQuestionResponse>;
  proposed_contract?: ContractRecord | null;
};

export type ContractActivationRequest = {
  contract_id: string;
  expected_version: number;
  expected_active_task_id?: string | null;
};

export type ContractActivationResponse = {
  active_contract: ContractRecord;
};

export type ApprovalDecisionRequest = {
  typed_target?: string | null;
};

export type ApprovalActionResponse = {
  approval_id: string;
  status: "approved" | "denied";
  retry?: EvaluateResponse | null;
};

export type AuditListResponse = {
  events: Array<AuditEvent>;
};
