"""Generate display types for the web client from FastAPI control schemas."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from sentinel.api.control_schemas import (  # noqa: E402
    AcceptedContractDraft,
    ActiveAuthorityResponse,
    ApprovalActionResponse,
    ApprovalDecisionRequest,
    ApprovalListResponse,
    AuditListResponse,
    ContractActivationRequest,
    ContractActivationResponse,
    ContractDraftRequest,
    ContractDraftResponse,
    ControlStatusResponse,
)

OUTPUT = ROOT / "web" / "src" / "lib" / "control-types.ts"
MODELS = (
    ControlStatusResponse,
    ActiveAuthorityResponse,
    ApprovalListResponse,
    ContractDraftRequest,
    ContractDraftResponse,
    AcceptedContractDraft,
    ContractActivationRequest,
    ContractActivationResponse,
    ApprovalDecisionRequest,
    ApprovalActionResponse,
    AuditListResponse,
)


def _schema(model: type[Any]) -> dict[str, Any]:
    if hasattr(model, "model_json_schema"):
        return model.model_json_schema()
    return model.schema()


def _typescript_type(schema: dict[str, Any], indent: int = 0) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(
            dict.fromkeys(_typescript_type(item, indent) for item in schema["anyOf"])
        )
    if "allOf" in schema:
        return " & ".join(_typescript_type(item, indent) for item in schema["allOf"])

    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(
            _typescript_type({**schema, "type": selected}, indent)
            for selected in kind
        )
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        return f"Array<{_typescript_type(schema.get('items', {}), indent)}>"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if properties:
            lines = ["{"]
            for name, value in properties.items():
                optional = "" if name in required else "?"
                rendered = _typescript_type(value, indent + 1)
                padding = "  " * (indent + 1)
                lines.append(f"{padding}{name}{optional}: {rendered};")
            lines.append(f"{'  ' * indent}}}")
            return "\n".join(lines)
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {_typescript_type(additional, indent)}>"
        return "Record<string, unknown>"
    return "unknown"


def render_types() -> str:
    definitions: dict[str, dict[str, Any]] = {}
    entries: list[tuple[str, dict[str, Any]]] = []
    for model in MODELS:
        schema = _schema(model)
        for name, definition in schema.pop("$defs", {}).items():
            existing = definitions.get(name)
            if existing is not None and existing != definition:
                raise ValueError(f"conflicting JSON schema definition: {name}")
            definitions[name] = definition
        entries.append((model.__name__, schema))

    sections = [
        "// Generated by scripts/generate_control_types.py.",
        "// FastAPI schemas are authoritative; do not edit this file manually.",
        "",
    ]
    for name in sorted(definitions):
        sections.append(
            f"export type {name} = {_typescript_type(definitions[name])};\n"
        )
    for name, schema in entries:
        if name in definitions:
            continue
        sections.append(f"export type {name} = {_typescript_type(schema)};\n")
    return "\n".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_types()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print("web control types are stale", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
